import OpenAI from 'openai';

let groqClients: OpenAI[] = [];
let geminiApiKeys: string[] = [];
let currentProvider: 'groq' | 'gemini' = 'groq';

let currentGroqIndex = 0;
let currentGeminiIndex = 0;

export function initAIClient(provider: 'groq' | 'gemini', groqKeys: string[], geminiKeys: string[]) {
  currentProvider = provider;
  
  groqClients = groqKeys.filter(k => k.trim()).map(key => new OpenAI({
    apiKey: key.trim(),
    baseURL: 'https://api.groq.com/openai/v1',
    dangerouslyAllowBrowser: true,
  }));
  currentGroqIndex = 0;

  geminiApiKeys = geminiKeys.filter(k => k.trim());
  currentGeminiIndex = 0;
}

export function switchProvider(provider: 'groq' | 'gemini') {
  currentProvider = provider;
}

export async function getInterviewAnswer(
  transcript: string, 
  resumeText1: string, 
  resumeText2: string,
  resumePriority: number,
  personalContext: string,
  interviewTitle: string, 
  imageBase64: string,
  onChunk: (chunk: string) => void, 
  onStart: (info: {provider: string, index: number}) => void = () => {}
) {
  if (currentProvider === 'groq' && groqClients.length === 0) return;
  if (currentProvider === 'gemini' && geminiApiKeys.length === 0) return;

  try {
    let contextPrompt = '';
    
    if (personalContext) {
      contextPrompt += `\n\n--- PERSONAL CONTEXT (ABSOLUTE HIGHEST PRIORITY) ---\nThis is about the candidate's core identity, strengths, weaknesses, and background. You MUST use this first for any personal or behavioral questions:\n${personalContext}`;
    }

    if (resumeText1 || resumeText2) {
      contextPrompt += `\n\n--- RESUMES ---\nUse these resumes to answer questions about past experience, projects, and skills.`;
      if (resumeText1 && resumePriority === 1) contextPrompt += `\n[RESUME 1 (HIGH PRIORITY - Primary focus for background)]\n${resumeText1}`;
      else if (resumeText1) contextPrompt += `\n[RESUME 1]\n${resumeText1}`;
      
      if (resumeText2 && resumePriority === 2) contextPrompt += `\n[RESUME 2 (HIGH PRIORITY - Primary focus for background)]\n${resumeText2}`;
      else if (resumeText2) contextPrompt += `\n[RESUME 2]\n${resumeText2}`;
    }

    const systemPrompt = `You are a job candidate in a live interview${interviewTitle ? ` for the role of ${interviewTitle}` : ''}. 
CRITICAL RULE: You MUST speak EXACTLY like a real, casual human being talking out loud. 100% human-like.
- Keep it medium length (around 3 to 5 sentences). Give a highly detailed, technically impressive, and highly accurate explanation without rambling. Never use bullet points.
- Do NOT sound like an AI assistant. Use everyday, simple conversational English. DO NOT use complex, robotic vocabulary.

CRITICAL INSTRUCTION FOR ACCURACY: The interview transcript is generated by Speech-to-Text and may contain typos or misheard words. Infer the true technical intent of the interviewer's question using context clues, and give the accurate answer to the INTENDED question.
If the user provides an image (screenshot), analyze the code or diagram in the screenshot to accurately answer the question.

CRITICAL OUTPUT RULE: YOU MUST OUTPUT *ONLY* THE EXACT WORDS THE CANDIDATE WILL SPEAK ALOUD. DO NOT include any reasoning, internal monologue, or explanation. DO NOT start with "Here's my answer", "Okay, so this screenshot", or "Assuming the interviewer means...". Just start speaking the answer immediately. NEVER acknowledge that you are looking at an image or screenshot.

CRITICAL EXPERTISE RULE: YOU ARE AN ABSOLUTE EXPERT. NEVER say you are "not familiar" or "don't know much" about a technology. If the interviewer asks about a framework or tool (like React), you MUST confidently answer the question as an expert, drawing from the resume if it's there, or just providing a technically brilliant, confident answer. NEVER diminish your own skills.

CRITICAL INSTRUCTION: If context is provided below, use it ONLY if the interviewer asks personal questions like "tell me about yourself", "what is your experience", or questions explicitly about your background. If they ask a general or technical question, just answer the technical question directly.
When asked about yourself, ACT AS THIS PERSON. Use the specific name, education, tools, and past projects from the context. Do NOT give a meta-answer.${contextPrompt}`;

    let userPrompt = '';
    if (imageBase64) {
      userPrompt = `Here is a screenshot related to the interview. Based on this image and the transcript, provide the perfect answer.
CRITICAL RULE: DO NOT acknowledge the screenshot in your response. NEVER say "in this screenshot", "the image shows", "Okay, so this screenshot", or "Okay, so". Just speak the answer naturally.

Interview transcript so far:
${transcript}

Respond directly to the interviewer as the candidate. Speak your answer now. START IMMEDIATELY WITHOUT INTRODUCTORY FILLER. DO NOT START WITH "Hi, I'm" or "Yeah, definitely" or "Well":`;
    } else {
      userPrompt = `Interview transcript so far:\n${transcript}\n\nRespond directly to the interviewer as the candidate. Speak your answer now. START IMMEDIATELY WITHOUT INTRODUCTORY FILLER. DO NOT START WITH "Hi, I'm" or "Yeah, definitely" or "Well":`;
    }

    if (currentProvider === 'groq' && groqClients.length > 0) {
      const client = groqClients[currentGroqIndex];
      const usedIndex = currentGroqIndex;
      currentGroqIndex = (currentGroqIndex + 1) % groqClients.length;
      
      onStart({ provider: 'groq', index: usedIndex + 1 });
      
      const messages: any[] = [
        { role: 'system', content: systemPrompt },
      ];
      
      if (imageBase64) {
        messages.push({ 
          role: 'user', 
          content: [
            { type: 'text', text: userPrompt },
            { type: 'image_url', image_url: { url: imageBase64 } }
          ]
        });
      } else {
        messages.push({ role: 'user', content: userPrompt });
      }

      let stream: any = null;
      
      if (imageBase64) {
        const visionModels = [
          'llama-3.2-11b-vision-preview',
          'llama-3.2-90b-vision-preview',
          'llama-3.2-11b-vision-instruct',
          'llama-3.2-90b-vision-instruct',
          'llama-3.2-11b-vision',
          'llama-3.2-90b-vision',
          'llama-4-scout-17b-16e-instruct',
          'meta-llama/llama-4-scout-17b-16e-instruct'
        ];
        
        let lastError = null;
        for (const modelName of visionModels) {
          try {
            stream = await client.chat.completions.create({
              model: modelName,
              messages,
              stream: true,
              temperature: 0.5,
            });
            console.log("Successfully connected to Groq vision model:", modelName);
            break;
          } catch (err: any) {
            lastError = err;
            console.warn(`Groq vision model ${modelName} failed or decommissioned. Trying next...`);
          }
        }
        if (!stream) {
          throw new Error(`All Groq vision models failed. Last error: ${lastError?.message}`);
        }
      } else {
        stream = await client.chat.completions.create({
          model: 'llama-3.1-8b-instant',
          messages,
          stream: true,
          temperature: 0.5,
        });
      }

      for await (const chunk of stream) {
        const content = chunk.choices[0]?.delta?.content || '';
        onChunk(content);
      }
    } else if (currentProvider === 'gemini' && geminiApiKeys.length > 0) {
      const key = geminiApiKeys[currentGeminiIndex];
      const usedIndex = currentGeminiIndex;
      currentGeminiIndex = (currentGeminiIndex + 1) % geminiApiKeys.length;
      
      onStart({ provider: 'gemini', index: usedIndex + 1 });
      
      const geminiModels = ['gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-pro', 'gemini-1.0-pro-vision-latest'];
      let response: Response | null = null;
      let lastGeminiError = '';

      for (const modelName of geminiModels) {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:streamGenerateContent?alt=sse&key=${key.trim()}`;
        const geminiContents: any[] = [];
        let geminiParts: any[] = [{ text: userPrompt }];
        if (imageBase64) {
          const mimeType = imageBase64.split(';')[0].split(':')[1] || 'image/png';
          const base64Data = imageBase64.split(',')[1] || imageBase64;
          geminiParts.push({
            inlineData: { mimeType, data: base64Data }
          });
        }
        geminiContents.push({ parts: geminiParts });

        response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            systemInstruction: { parts: [{ text: systemPrompt }] },
            contents: geminiContents,
            generationConfig: { temperature: 0.1, maxOutputTokens: 150 }
          })
        });

        if (response.ok) {
          console.log(`Successfully connected to Gemini model: ${modelName}`);
          break;
        } else {
          const errText = await response.text();
          lastGeminiError = errText;
          console.warn(`Gemini model ${modelName} failed. Trying next...`);
        }
      }

      if (!response || !response.ok) {
         throw new Error(`Gemini API Error: All models failed. Last error: ${lastGeminiError}`);
      }

      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      let buffer = '';
      
      while (reader) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        let nlIndex;
        while ((nlIndex = buffer.indexOf('\n')) !== -1) {
          const line = buffer.slice(0, nlIndex);
          buffer = buffer.slice(nlIndex + 1);
          
          if (line.startsWith('data: ')) {
            const dataStr = line.slice(6).trim();
            if (dataStr === '[DONE]') continue;
            try {
              const data = JSON.parse(dataStr);
              if (data.candidates && data.candidates[0]?.content?.parts) {
                const text = data.candidates[0].content.parts[0].text;
                if (text) onChunk(text);
              }
            } catch (e) {
              // Ignore partial JSON parse errors if still fragmented
            }
          }
        }
      }
    }
  } catch (error: any) {
    console.error('AI Error:', error);
    onChunk(`\n[AI Error: ${error.message || error}]`);
  }
}
